name: Destroy Infrastructure

on:
  workflow_dispatch

jobs:
  destroy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Create RDS Snapshot
        run: |
          aws rds create-db-snapshot \
            --db-instance-identifier writing-analyzer-db \
            --db-snapshot-identifier writing-analyzer-snapshot-$(date +%s)

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
